# This file should be ran through ./dev.sh

version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - 9000:8080
    environment:
      - "CLIENT_ID=${CLIENT_ID}"
      - "CLIENT_SECRET=${CLIENT_SECRET}"

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - "./web/http.prod.conf:/etc/nginx/conf.d/default.conf"

networks:
  default:
    name: containers
    driver: bridge
