# This file should be ran through ./dev.sh

version: '3.9'

services:
  loki:
    container_name: loki
    image: grafana/loki:2.6.1
    volumes:
      - ./monitoring/loki/config:/etc/loki
      - ./monitoring/loki/data:/data/loki
    ports: 
      - "3100:3100"

  promtail:
    container_name: promtail
    image: grafana/promtail:2.6.1
    volumes:
      - /var/log:/var/log:ro
      - ./monitoring/promtail:/etc/promtail

  grafana:
    user: ${USER_UID}
    container_name: grafana
    image: grafana/grafana:9.1.7
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
  
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - 9000:8080
    environment:
      - "CLIENT_ID=${CLIENT_ID}"
      - "CLIENT_SECRET=${CLIENT_SECRET}"

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - "./web/http.prod.conf:/etc/nginx/conf.d/default.conf"

networks:
  default:
    name: containers
    driver: bridge
