# This file should be ran through ./dev.sh

version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        user: "${USER}"
        uid: "${USER_UID}"
        gid: "${USER_GID}"
    ports:
      - 9000:8080
    volumes:
      - ./backend:/app
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
    environment:
      - "http_proxy=host.docker.internal:8000"
      - "https_proxy=host.docker.internal:8000"
      - "CLIENT_ID=${CLIENT_ID}"
      - "CLIENT_SECRET=${CLIENT_SECRET}"
    user: "${USER}"
    command: air

  frontend:
    container_name: frontend
    build:
      context: ./web/frontend
      dockerfile: Dockerfile.dev
      args:
        user: "${USER}"
        uid: "${USER_UID}"
        gid: "${USER_GID}"
    ports:
      - 9001:8080
    volumes:
      - ./web/frontend:/app
    user: "${USER}"
    command: sh -c "yarn && yarn dev --host 0.0.0.0 --port 8080"

  web:
    container_name: web
    image: nginx:1.23-alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - "./web/http.dev.conf:/etc/nginx/conf.d/default.conf"

networks:
  default:
    name: containers
    driver: bridge
