FROM golang:1.19-bullseye

RUN go install github.com/cosmtrek/air@latest

WORKDIR /app

ARG user
ARG uid
ARG gid

RUN adduser --disabled-password --uid $uid --gecos "" $user && \
    chown -R $user /go
